# Generated by Django 5.1.4 on 2025-01-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_profile_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
