# Generated by Django 5.1.4 on 2025-01-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="users/profiles/"),
        ),
    ]
