# Generated by Django 5.1.4 on 2025-01-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_author_bio_alter_author_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="follower_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="author",
            name="following_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
